### ISSUE TITLE
Turborepo + Windows + Docker

### ISSUE THREAD

**Issue by phoenixVS** [martpie/next-transpile-modules#261]
Using pnpm with turborepo running in Docker (with compose) next-transpile-module doesn't see packages/ui/

**To Reproduce**
Run in root
pnpm install
docker-compose up app

**Setup**
- Next.js version: 12.0.8
- `next-transpile-modules` version:9
- Node.js version:16.15
- `npm`/`yarn` version:pnpm latest
- Operating System: Windows
- Webpack 5

Dockerfile
```
FROM node:14-alpine

ENV NODE_ENV development

RUN npm install -g pnpm
RUN apk add git

WORKDIR /app

COPY  ["pnpm-lock.yaml", "pnpm-workspace.yaml", "package.json", "./"]

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store\
      pnpm fetch

COPY . ./

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store\
     pnpm -r install --frozen-lockfile --offline

EXPOSE 3000 3001 1337

CMD ["pnpm", "run", "dev"]
```

next.config.js
```
const withTM = require("next-transpile-modules")(["ui"]);
module.exports = withTM({ reactStrictMode: true });
```

apps/landing/package.json
```
{
  "name": "landing",
  "version": "0.1.1",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.0.8",
    "next-compose-plugins": "^2.2.1",
    "next-pwa": "^5.5.2",
    "next-transpile-modules": "9",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "ui": "workspace:*"
  },
  "devDependencies": {
    "@babel/core": "^7.17.10",
    "@types/node": "^17.0.12",
    "@types/react": "17.0.37",
    "config": "workspace:*",
    "eslint": "7.32.0",
    "tsconfig": "workspace:*",
    "typescript": "^4.5.3",
    "webpack": "^5.72.0"
  },
  "peerDependencies": {
    "@babel/core": "^7.17.10",
    "webpack": "^5.72.0"
  }
}
```

packages/ui/package.json
```
{
  "name": "ui",
  "version": "0.0.0",
  "main": "./index.tsx",
  "types": "./index.tsx",
  "license": "MIT",
  "devDependencies": {
    "@types/react": "^17.0.37",
    "@types/react-dom": "^17.0.11",
    "tsconfig": "workspace:*",
    "config": "workspace:*",
    "typescript": "^4.5.3"
  }
}
```
![Screenshot 2022-05-10 161549](https://user-images.githubusercontent.com/28185581/167637761-b16153ba-0aab-47a1-9a10-fb4ef08bbbd1.png)

**Comment by martpie** [comment]
So let's isolate things here. First, does it work without Docker on a local setup first?

**Comment by phoenixVS** [comment]
pnpm run build
pnpm run dev
Works correct

**Comment by phoenixVS** [comment]
Maybe problem is relative with using docker volumes for node_modules

Here is docker-compose.yml
```
version: '3.9'
  
services:
  
  app: &app
    container_name: gxpaas
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "1337:1337"
    volumes:
      - .:/app
      - /app/node_modules
        
  db:
   image: cockroachdb/cockroach:v19.2.2
   ports:
     - "26257:26257"
     - "8080:8080"
   command: start-single-node --insecure
   volumes:
     - "./cockroach-data/crdb:/cockroach/cockroach-data"


networks:
  turbo-network:
    driver: bridge
```
